version: "3"

services:
  mom:
    image: "rabbitmq:3-management"
    hostname: rabbit
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
  client:
    depends_on:
      - mom
    build:
      dockerfile: Dockerfile
      context: ./ufoclient
    restart: on-failure
    volumes:
      - ./ufoclient/build/libs/:/app
  add-subtract:
    depends_on:
      - mom
    build:
      dockerfile: Dockerfile
      context: ./add-subtract-service
    restart: on-failure
    volumes:
      - ./add-subtract-service/build/libs/:/app
  multiply-divide:
    depends_on:
      - mom
    build:
      dockerfile: Dockerfile
      context: ./multiply-divide-service
    restart: on-failure
    volumes:
      - ./multiply-divide-service/build/libs/:/app
